# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# box sizing
VB_MEMORY=1024
VB_CPUS=1

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  # Every Vagrant environment requires a box to build off of.
  config.vm.box = "bento/centos-6.7"  
  
  # size of the box
  config.vm.provider :virtualbox do |vb|
    vb.memory = VB_MEMORY
    vb.cpus = VB_CPUS
  end
  
  # disable typical plug-ins
  if Vagrant.has_plugin?("vagrant-delphix") then
    # manage /etc/hosts on both host & guests
    puts "Plugin installed."
  end
  
end
